### ISSUE TITLE
Link broken in pull request template

### ISSUE THREAD

**Issue by varunzxzx** [UdacityMobileWebScholarship/blood-donation#11]
# Guidelines to submit an issue

#### I'm opening this issue because:

  - [ ] App is crashing.
  - [ ] I think I've found a bug.
  - [ ] App is doing something, I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Contributing guidelines link is broken in pull request template.

### Supporting Information:

 - [ ] `node -v` prints:
 - [ ] Windows, OS X/macOS, or Linux?:

**Comment by optimistanoop** [comment]
@varunzxzx  I can see link working fine in dev branch in pull request template, kindly elaborate on this.

**Comment by varunzxzx** [comment]
We should add the whole URL instead of a relative path to the file, visiting this link from any other page will lead to 404.

**Comment by optimistanoop** [comment]
@varunzxzx Thanks, got it.

**Comment by varunzxzx** [comment]
Closing the issue as the issue is resolved in #15
