### ISSUE TITLE
Link broken in issue template

### ISSUE THREAD

**Issue by varunzxzx** [UdacityMobileWebScholarship/blood-donation#12]
# Guidelines to submit an issue

#### I'm opening this issue because:

    - [ ] I think I've found a bug.
  - [ ] App is crashing.
- [ ] App is doing something, I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
A link is broken in issue template

### Supporting Information:

 - [ ] `node -v` prints:
 - [ ] Windows, OS X/macOS, or Linux?:

**Comment by skarthikeyan96** [comment]
There are no links present in the issue-template.md @varunzxzx

**Comment by varunzxzx** [comment]
@skarthikeyan96 it is in the comments.

**Comment by skarthikeyan96** [comment]
Got it and fixed that @varunzxzx. Can you close the issue#12.

**Comment by varunzxzx** [comment]
Closing as the issue is resolved in #13
